### ISSUE TITLE
Add warning for illegal initializers for props

### ISSUE THREAD

**Issue by digitalheir** [HerringtonDarkholme/av-ts#24]
I have component

````ts
import { Vue, Prop, Component } from 'av-ts'

@Component({name: 'best-girl'})
class BestGirl extends Vue {
  @Prop name:string = "Asuka"
  @Prop isBest:boolean = true
}
````

I try to use it:

````html
<best-girl @click="hello" girl="Rem" :isBest="false"/>
````

I get error:

````
Uncaught TypeError: Cannot create property 'type' on string 'Asuka'
````

We can trace the error back to `prop.ts`:

````ts
Component.register(PROP_KEY, function(proto, instance, options) {
  let propKeys: string[] = proto[PROP_KEY]
  let props = options.props = options.props || createMap()

  for (let key of propKeys) {
    let prop: PropOptions = {}
    if (instance[key] != null) {
      prop = instance[key]
      delete instance[key]
    }
    // refill type if not existing, do we need this?
    if (!prop.type) { // Error happens here because we can't set .type on numbers, booleans and strings
      prop.type = getReflectType(proto, key)
    }
    props[key] = prop
  }
  options.props = props
})
````

I guess I should have wrapped the property in a magic `p` function. But that's not really obvious. Should you not at least provide a warning that we can't use primitive types like this, or else wrap the value in an object for the user's sake?

**Comment by digitalheir** [comment]
Oops, I used the API wrongly

**Comment by HerringtonDarkholme** [comment]
Hi, thanks for filing this.

This is by design (at least when I first design the API of av-ts). Because `p` is a special magic function that transforms Vue's prop configuration object to a token with corresponding type.

Just as you cannot use primitive value in Vue's original API to declare props, you cannot do it in av-ts either.

Thanks for your understanding.

**Comment by digitalheir** [comment]
I'm reopening because I'm not stupid and I still did it wrong: this is not intuitive behaviour. I think the user should be guided more.

**Comment by HerringtonDarkholme** [comment]
No, it is not intuitive, and it should not. 

If primitive data are allowed in props, then all other data type should be allowed in props fields for consistency. But then it is quite confusing for allowing both `@Prop myProp = p(config)` and `@Prop anotherProp = someObj`.

If it is a prop, it should look like differently from `data`.

More background: the current Prop design maximizes conciseness, you won't repeat your self to annotate the property and adding configuration in Prop decorator. You would generally do it in other libraries. To be DRY enough, I sacrifice intuitiveness, since you will encounter the problem soon and if a user does not like it, the user will know and learn it instantly.

**Comment by digitalheir** [comment]
Ok, I agree. I still think we might add a warning in `prop.ts`

    if (typeof prop !== 'object' && !prop.type)
        throw new Error("Unlawful use of property API, did you remember to define the property by wrapping it into the p function (import {p} from 'av-ts')?");

Do you agree?

**Comment by HerringtonDarkholme** [comment]
In general, it is not enough. Because users can pass custom objects to props. To tell a real prop returned by `p` from others we need an additional field, that's one more overhead.

**Comment by HerringtonDarkholme** [comment]
Since I have already done a lot of awful code in collecting data. I don't mind adding more awful implementation.

Users can choose whether to use an efficient implementation or to write less code,

**Comment by HerringtonDarkholme** [comment]
Hmm, it seems hard to do that because my test code already exploit custom `p` function.

The ROI is quite low for this functionality, I think.
