### ISSUE TITLE
Watch not triggering function on change to select

### ISSUE THREAD

**Issue by roryprimrose** [HerringtonDarkholme/av-ts#30]
I'm not able to have the Watch directive call my function. The select has the correct data being bound to it with the value selected correctly. Changing the value in the select does not trigger the watch function.

I have the following in my view:

```
<select v-model="selectedBillingCycle">
    <option v-for="billingCycle in billingCycles" v-bind:value="billingCycle.name">{{ billingCycle.name }}</option>
</select>
```

My TypeScript then has the following:

```
    public selectedBillingCycle: string;

    @Watch("selectedBillingCycle")
    public changePackages(oldValue: string, newValue: string): void {
        console.log("Loading packages for " + this.selectedCurrency + " and " + this.selectedBillingCycle);

        this.loadPackages();
    }
```

Is this an issue with my implementation or Watch? I'm using av-ts 0.6.1 and TypeScript 2.1.4.

**Comment by roryprimrose** [comment]
Ah, you wouldn't believe it. I solved this three minutes after posting. The issue is that the declaration of ```public selectedBillingCycle: string``` does not exist on the object until a value is assigned to it later, at which point the watch code has already try to bind to it.

The fix is to change the declaration to ```public selectedBillingCycle: string = ""```

Perhaps you could log a warning if the watched item does not exist on the component.

**Comment by HerringtonDarkholme** [comment]
Thanks for trying out av-ts.

> Perhaps you could log a warning if the watched item does not exist on the component.

I think this is technically impossible for av-ts. Since it is just a library to write option in class syntax. By the time av-ts collects watch option, it has no idea what a component has in data. And for property without initialization, TS does not generate code at all! So av-ts cannot tell you have an uninitialized data property. Both precludes the possibility for a warning.
