### ISSUE TITLE
Single type definition file for all vue files

### ISSUE THREAD

**Issue by gldraphael** [HerringtonDarkholme/av-ts#39]
Right now, I need to create a type definition file for each `.vue` with the following contents:

```typescript
import Vue = require('vue')

declare var exp: Vue
export default exp
```

Anyway I can just do with one `*.vue.d.ts` file?

**Comment by HerringtonDarkholme** [comment]
Adding your own `typing.d.ts`

```ts
import * as VueG from 'vue'
declare var Vue: typeof VueG
```

**Comment by gldraphael** [comment]
Where do I add this?

Also, the template has a `app.vue.d.ts` file. [Link](https://github.com/HerringtonDarkholme/av-ts-template/blob/master/template/src/app.vue.d.ts).
The template requires every `vue` file to have a `vue.d.ts` file. I'm hoping the `typings.d.ts` file you mentioned will save me from having redundant files.

**Comment by HerringtonDarkholme** [comment]
Please read the TypeScript handbook. Especially the declaration file part. https://www.typescriptlang.org/docs/handbook/declaration-files/introduction.html

**Comment by gldraphael** [comment]
Thanks! I'll check these out.

**Comment by gazugafan** [comment]
I'm a little confused about this too, gldraphael. If you get it figured out, please come back and post your findings!

**Comment by gldraphael** [comment]
@gazugafan I got it working by making the `vue-loader` use `vue-ts-loader` to handle `ts` code. [Here's my `webpack.config.js` file](https://gist.github.com/gldraphael/b7c84eaf5d77e2a2e538c53572e68607).

```javascript
  // ...
  vue: {
    // instruct vue-loader to load TypeScript
    loaders: { 
      js: 'vue-ts-loader', 
      less: 'css!less',
      ts: 'vue-ts-loader'
    },
    // make TS' generated code cooperate with vue-loader
    esModule: true
  },
  // ...
```

VS Code still shows the `Cannot find module './path/to/file.vue'.` for every `.vue file`.

But Webpack (and the dev console) shows this error
> error TS2307: Cannot find module './app.vue'.

only for the `app.vue` file. I'm yet to find what's causing it. I'm guessing it's got to do with `webpack.config.js`.

Good news is that, despite the errors the app _works_ fine. So this should do for the time being.

**Comment by gazugafan** [comment]
@gldraphael Yeah, I've got it compiling down without associated .vue.d.ts files. No webpack or TSC errors. I'm using ts-loader (not vue-ts-loader), which should work fine if you include lang="ts" in the script tag within your vue files.

My only real problem is how to deal with the IDE errors. Neither VS Code or PHPStorm seem to be able to inspect the TypeScript inside a vue file. So, the IDE thinks the vue file imports are invalid, and complain with a "Cannot find module" error. As far as I can tell, there's no way around this, except to include an associated vue.d.ts file. I think I'm just going to ignore the IDE errors and move on.

Any other suggestions @HerringtonDarkholme?

**Comment by HerringtonDarkholme** [comment]
Adding a new ambient declaration.

```ts
declare module "*.vue"
```

**Comment by gazugafan** [comment]
Witchcraft!
