### ISSUE TITLE
comparison with other vue typescript libraries

### ISSUE THREAD

**Issue by davidmoshal** [HerringtonDarkholme/av-ts#7]
Hi, am moving our discussion from the vue-typescript issues,   
seems like `vue-typescript` is dormant at Vue 1.x, so am looking for an alternative.

am wondering how `av-ts` project compares with:
- https://libraries.io/npm/vue-typescript-component
- https://github.com/vuets/vuets

David

**Comment by HerringtonDarkholme** [comment]
Hi David, thanks for giving av-ts a look. 

This is my repo, so pardon me for being showy.

I have seen a lot of vue's typescript binding libraries, so below is my own observation.

1. Compatibility

All of the three libraries, vue-typescript-component, vuets and av-ts, have good support for Vue2 and TS2. So there is not much to compare here. (vuets has vue1.0 support while the other two do not)

2. Extensibility

I think this the best part of av-ts. av-ts provides a `Component.register` for custom decorator. For example, if you want to use vuex in your project but also want to preserve type safety, you can create your own decorator. This is exactly what I do in [kilimanjaro](https://github.com/HerringtonDarkholme/kilimanjaro), a typed vuex fork.

vue-ts-copmonent does not provide extensibility at all. vue-ts has the same extensibility as original vue because it uses object literal style (that is, the most extensible one among the three). However, vuets also support class component like syntax. Mixing two style is somewhat confusing.

3. Idiom


// TODO, it is not a complete list. Pardon me

**Comment by davidmoshal** [comment]
@HerringtonDarkholme Wow, thanks for the thorough review.   

Actually, you missed at least 2 more benefits of your project!   
`av-ts` has:
- [vue-ts-loader](https://github.com/HerringtonDarkholme/vue-ts-loader) which is the only way I've seen so far to combine typescript in a .vue file!
- you have an excellent [introductory guide](http://herringtondarkholme.github.io/2016/10/03/vue2-ts2/)
 
Problem for me remains that I have to refactor out the `.sync` two-way binding.    

Can I make 2 suggestions:  
1. create a vue clie template, e.g  https://github.com/danielschmitz/vue-typescript-template
2. create a example showing the most concise, idiomatic, way of replacing .sync.

Thanks again for the comparison, I'll experiment with it (and vue-typescript-component) over the weekend.    

It does sound like vuets is out due to lack of ts idioms (that's common to all the other vue ts libraries I think).

David

**Comment by HerringtonDarkholme** [comment]
You can refer to this http://vuejs.org/guide/migration.html#once-and-sync-Modifiers-on-v-bind-removed.

I don't think there is one true way to replace `.sync`. But av-ts does support `$emit` and vuex.

**Comment by HerringtonDarkholme** [comment]
Wow, vue-cli is amazing https://github.com/HerringtonDarkholme/av-ts-template

Thanks for introducing it to me!

**Comment by davidmoshal** [comment]
> I don't think there is one true way to replace .sync. But av-ts does support $emit and vuex.

That's exactly my point, the greater the number of choices, the longer the decision takes (sales 101).
And... the choices so far have been significantly more verbose than `.sync`.

Put it this way: the first project to show the most idiomatic, least verbose, way to handle the various features deprecated in Vue 2.0 will capture the most users looking for the most efficient upgrade path.

Dave

**Comment by HerringtonDarkholme** [comment]
Sorry, I really cannot help you here. vue's doc has stated it clearly. You have three options. And these three options suit for different scenarios. $emit for small app, vuex for full blown medium to large app. Custom input for a reusable component.

If you really want an answer from me then it would be vuex. (well, at least it can scale large)

**Comment by davidmoshal** [comment]
I'll send you and example of a problem I have, namely a generic component that is 2-way bound.

i.e: Vuex is great for a specific data item, but what about a generic component, where the data to be bound needs to be delayed until the component is used?    
-- not that obvious how to solve (at least to me at this point).

**Comment by HerringtonDarkholme** [comment]
Please don't. Github issues isn't for Q&A. 

You can ask questions on https://gitter.im/vuejs/vue and http://forum.vuejs.org/

**Comment by davidmoshal** [comment]
fair enough.

**Comment by davidmoshal** [comment]
@HerringtonDarkholme hi, you probably saw from the links that we've still not moved off vue-component and Vue 1, so am re-examining these libraries.

Seems like vue-class-component is a new addition since we last looked, and has input from Evan You.

Any benefits to av-ts over vue-class-component?

Dave

**Comment by HerringtonDarkholme** [comment]
No, please use vue-class-component. It is officially supported.

**Comment by davidmoshal** [comment]
thanks, given how close vue-class-component is to yours, I'm giving you credit for its inspiration!
Dave
